### ISSUE TITLE
Не работает создание пользователя

### ISSUE THREAD

**Issue by ig-rudenko** [SemyonYankovskiy/collectioncoin_bot#1]
## При регистрации нового пользователя выскакивает ошибка

coin_bot_1  | Traceback (most recent call last):
coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
coin_bot_1  |     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
coin_bot_1  |     return await asyncio.gather(*tasks)
coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
coin_bot_1  |     response = await handler_obj.handler(*args, **partial_data)
coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
coin_bot_1  |     return await self.message_handlers.notify(update.message)
coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
coin_bot_1  |     response = await handler_obj.handler(*args, **partial_data)
coin_bot_1  |   File "/app/main.py", line 175, in process_password
coin_bot_1  |     user.save()
coin_bot_1  |   File "/app/database.py", line 167, in save
coin_bot_1  |     db.cursor.execute(
coin_bot_1  | sqlite3.OperationalError: no such column: None

## Решение

Надо прописать в файле `database.py` при создании пользователя `self.new_messages or 0`
```python
db.cursor.execute(
    f"INSERT INTO users (tg_id, email, password, new_messages, new_swap ) "
    f"VALUES ('{self.telegram_id}', '{self.email}', '{self.password}', {self.new_messages or 0}, {self.new_swap or 0})"
)
```

**Comment by SemyonYankovskiy** [comment]
Исправлено
