### ISSUE TITLE
Не работает регистрация пользователя

### ISSUE THREAD

**Issue by ig-rudenko** [SemyonYankovskiy/collectioncoin_bot#2]
## Ошибка

> coin_bot_1  | Traceback (most recent call last):
> coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
> coin_bot_1  |     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
> coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
> coin_bot_1  |     return await asyncio.gather(*tasks)
> coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
> coin_bot_1  |     response = await handler_obj.handler(*args, **partial_data)
> coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
> coin_bot_1  |     return await self.message_handlers.notify(update.message)
> coin_bot_1  |   File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
> coin_bot_1  |     response = await handler_obj.handler(*args, **partial_data)
> coin_bot_1  |   File "/app/main.py", line 158, in process_password
> coin_bot_1  |     file_name = download(user_coin_id, session)
> coin_bot_1  |   File "/app/site_calc.py", line 122, in download
> coin_bot_1  |     with open(file_name, "wb") as f:
> coin_bot_1  | FileNotFoundError: [Errno 2] No such file or directory: './users_files/32693_.xlsx'

## Решение

Необходимо создать папку в контейнере `users_files`.

**Comment by SemyonYankovskiy** [comment]
Исправлено
